apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: kube-system
  labels:
    app: nginx
spec:
  ports:
  - name: port1
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: kube-system
  labels:
    app: nginx
spec:
    containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
