apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: kube-system
  labels:
    app: webservice
spec:
  ports:
  - name: port1
    port: 5000
    targetPort: 5000
    nodePort: 31290
  selector:
    app: webservice
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: webservice
  namespace: kube-system
  labels:
    app: webservice
spec:
    containers:
    - name: webservice
      image: nitsteve99/image1
      ports:
      - containerPort: 5000
